package com.login.nativesso.i;

public interface b {
    public static final String A;
    public static final String B;
    public static final String C;
    public static final String D;
    public static final String E;
    public static final String F;
    public static final String G;
    public static final String H;
    public static final String I;
    public static final String J;
    public static final String K;
    public static final String L;
    public static final String M;
    public static final String N;
    public static final String a = d.a;
    public static final String b;
    public static final String c = d.b;
    public static final String d;
    public static final String e;
    public static final String f;
    public static final String g;
    public static final String h;
    public static final String i;
    public static final String j;
    public static final String k;
    public static final String l;
    public static final String m;
    public static final String n;
    public static final String o;
    public static final String p;
    public static final String q;
    public static final String r;
    public static final String s;
    public static final String t;
    public static final String u;
    public static final String v;
    public static final String w;
    public static final String x;
    public static final String y;
    public static final String z;

    static {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/app/getDataForDevice");
        b = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(c);
        stringBuilder.append("/msocialsite/app/v1googleplusresponse");
        d = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(c);
        stringBuilder.append("/msocialsite/app/linkedinresponse");
        e = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("uploadProfilePic");
        f = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(c);
        stringBuilder.append("/msocialsite/app/facebookresponse");
        g = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/app/identity/login/isValidPackage");
        h = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("getLoginOtp");
        i = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("verifyLoginOtpPassword");
        j = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("verifyLoginOtpPasswordGdpr");
        k = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("resendForgotPasswordOTP");
        l = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("getUserDetails");
        m = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("signOutUser");
        n = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("setPassword");
        o = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("changePassword");
        p = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("getNewTicket");
        q = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("getForgotPasswordOtp");
        r = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("verifyForgotPassword");
        s = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("registerUser");
        t = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("resendSignUpOtp");
        u = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("verifySignUpOTP");
        v = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("getSsecFromTicket");
        w = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("updateMobile");
        x = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("addAlternateEmail");
        y = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("verifyMobile");
        z = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("verifyAlternateEmail");
        A = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("updateUserDetails");
        B = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("updateUserPermissions");
        C = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("registerOnlyMobile");
        D = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("checkUserExists");
        E = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("validatepassword");
        F = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("verifyGsmaMobile");
        G = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("deleteUser");
        H = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("renewTicket");
        I = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("truecaller");
        J = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("delinkSocial");
        K = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("linkSocial");
        L = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("socialImageUpload");
        M = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append(a);
        stringBuilder.append("/sso/crossapp/identity/native/");
        stringBuilder.append("blockUserChannel");
        N = stringBuilder.toString();
    }
}
