package com.google.android.gms.ads.internal;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.location.Location;
import android.os.Bundle;
import com.google.android.gms.internal.ads.zzaba;
import com.google.android.gms.internal.ads.zzacf;
import com.google.android.gms.internal.ads.zzacp;
import com.google.android.gms.internal.ads.zzasi;
import com.google.android.gms.internal.ads.zzasj;
import com.google.android.gms.internal.ads.zzaxg;
import com.google.android.gms.internal.ads.zzbbi;
import com.google.android.gms.internal.ads.zzbbq;
import com.google.android.gms.internal.ads.zzwb;
import com.google.android.gms.internal.ads.zzwf;
import com.google.android.gms.internal.ads.zzyv;
import com.google.android.gms.internal.ads.zzzs;
import java.util.List;
import java.util.concurrent.Callable;
import org.json.JSONArray;
import org.json.JSONObject;

final class zzbe implements Callable<zzacf> {
    private final /* synthetic */ zzaxg zzblz;
    private final /* synthetic */ int zzbqf;
    private final /* synthetic */ JSONArray zzbqg;
    private final /* synthetic */ int zzbqh;
    private final /* synthetic */ zzbb zzbqi;

    zzbe(zzbb zzbb, int i, JSONArray jSONArray, int i2, zzaxg zzaxg) {
        this.zzbqi = zzbb;
        this.zzbqf = i;
        this.zzbqg = jSONArray;
        this.zzbqh = i2;
        this.zzblz = zzaxg;
    }

    public final /* synthetic */ Object call() throws Exception {
        if (this.zzbqf >= this.zzbqg.length()) {
            return null;
        }
        Bundle bundle;
        JSONArray jSONArray = new JSONArray();
        jSONArray.put(this.zzbqg.get(this.zzbqf));
        JSONObject jSONObject = new JSONObject();
        jSONObject.put("ads", jSONArray);
        zza zzbb = new zzbb(this.zzbqi.zzbls.zzsp, this.zzbqi.zzbly, this.zzbqi.zzbls.zzbst, this.zzbqi.zzbls.zzbsn, this.zzbqi.zzbma, this.zzbqi.zzbls.zzbsp, true);
        zzbb.zza(this.zzbqi.zzbls, zzbb.zzbls);
        zzbb.zzkm();
        zzbb.zza(this.zzbqi.zzblo);
        zzaba zzaba = zzbb.zzbln;
        int i = this.zzbqf;
        zzaba.zzg("num_ads_requested", String.valueOf(this.zzbqh));
        zzaba.zzg("ad_index", String.valueOf(i));
        zzasi zzasi = this.zzblz.zzeag;
        String jSONObject2 = jSONObject.toString();
        if (zzasi.zzdwg.extras != null) {
            bundle = new Bundle(zzasi.zzdwg.extras);
        } else {
            bundle = new Bundle();
        }
        Bundle bundle2 = bundle;
        bundle2.putString("_ad", jSONObject2);
        int i2 = zzasi.zzdwg.versionCode;
        long j = zzasi.zzdwg.zzcjb;
        int i3 = zzasi.zzdwg.zzcjc;
        List list = zzasi.zzdwg.zzcjd;
        boolean z = zzasi.zzdwg.zzcje;
        int i4 = zzasi.zzdwg.zzcjf;
        boolean z2 = zzasi.zzdwg.zzcjg;
        String str = zzasi.zzdwg.zzcjh;
        zzzs zzzs = zzasi.zzdwg.zzcji;
        Location location = zzasi.zzdwg.zzcjj;
        String str2 = zzasi.zzdwg.zzcjk;
        Location location2 = location;
        Bundle bundle3 = zzasi.zzdwg.zzcjl;
        Bundle bundle4 = zzasi.zzdwg.zzcjm;
        List list2 = zzasi.zzdwg.zzcjn;
        String str3 = zzasi.zzdwg.zzcjo;
        String str4 = zzasi.zzdwg.zzcjp;
        boolean z3 = zzasi.zzdwg.zzcjq;
        zzzs zzzs2 = zzzs;
        String str5 = str2;
        zzwb zzwb = new zzwb(i2, j, bundle2, i3, list, z, i4, z2, str, zzzs2, location2, str5, bundle3, bundle4, list2, str3, str4, z3, null, zzasi.zzdwg.zzcjs, zzasi.zzdwg.zzcjt);
        Bundle bundle5 = zzasi.zzdwf;
        zzwf zzwf = zzasi.zzbst;
        String str6 = zzasi.zzbsn;
        ApplicationInfo applicationInfo = zzasi.applicationInfo;
        PackageInfo packageInfo = zzasi.zzdwh;
        String str7 = zzasi.zzdwj;
        String str8 = zzasi.zzclm;
        zzbbi zzbbi = zzasi.zzbsp;
        Bundle bundle6 = zzasi.zzdwk;
        List list3 = zzasi.zzbtt;
        List list4 = zzasi.zzdwu;
        Bundle bundle7 = zzasi.zzdwm;
        zza zza = zzbb;
        boolean z4 = zzasi.zzdwn;
        int i5 = zzasi.zzdwo;
        int i6 = zzasi.zzdwp;
        float f = zzasi.zzbwv;
        String str9 = zzasi.zzdwq;
        Bundle bundle8 = bundle6;
        List list5 = list3;
        long j2 = zzasi.zzdwr;
        String str10 = zzasi.zzdws;
        List list6 = zzasi.zzdwt;
        String str11 = zzasi.zzbsm;
        zzacp zzacp = zzasi.zzbti;
        String str12 = zzasi.zzdww;
        float f2 = zzasi.zzdwx;
        boolean z5 = zzasi.zzdxd;
        int i7 = zzasi.zzdwy;
        int i8 = zzasi.zzdwz;
        boolean z6 = zzasi.zzdxa;
        boolean z7 = zzasi.zzdxb;
        Bundle bundle9 = bundle7;
        zzbca zzm = zzbbq.zzm(zzasi.zzdxc);
        String str13 = zzasi.zzdxe;
        boolean z8 = z7;
        boolean z9 = zzasi.zzdlv;
        int i9 = zzasi.zzdxf;
        Bundle bundle10 = zzasi.zzdxg;
        String str14 = zzasi.zzdxh;
        zzyv zzyv = zzasi.zzbtl;
        boolean z10 = zzasi.zzdxi;
        Bundle bundle11 = zzasi.zzdxj;
        z7 = zzasi.zzdxn;
        String str15 = str13;
        boolean z11 = z7;
        Bundle bundle12 = bundle9;
        String str16 = str15;
        List list7 = list4;
        zzwb zzwb2 = zzwb;
        PackageInfo packageInfo2 = packageInfo;
        String str17 = str7;
        str5 = str8;
        zzbbi zzbbi2 = zzbbi;
        Bundle bundle13 = bundle8;
        List list8 = list5;
        boolean z12 = z4;
        int i10 = i5;
        int i11 = i6;
        float f3 = f;
        String str18 = str9;
        long j3 = j2;
        String str19 = str10;
        List list9 = list6;
        String str20 = str11;
        zzacp zzacp2 = zzacp;
        String str21 = str12;
        float f4 = f2;
        boolean z13 = z5;
        int i12 = i7;
        int i13 = i8;
        boolean z14 = z6;
        boolean z15 = z8;
        boolean z16 = z9;
        int i14 = i9;
        Bundle bundle14 = bundle10;
        String str22 = str14;
        zzyv zzyv2 = zzyv;
        boolean z17 = z10;
        Bundle bundle15 = bundle11;
        boolean z18 = z11;
        zza zza2 = zza;
        zza2.zza(new zzasj(bundle5, zzwb2, zzwf, str6, applicationInfo, packageInfo2, str17, str5, zzbbi2, bundle13, list8, list7, bundle12, z12, i10, i11, f3, str18, j3, str19, list9, str20, zzacp2, str21, f4, z13, i12, i13, z14, z15, zzm, str16, z16, i14, bundle14, str22, zzyv2, z17, bundle15, z18, zzbbq.zzm(zzasi.zzdwi), zzasi.zzbtn, zzasi.zzdxo, zzasi.zzdxp, 1, zzasi.zzdxr, zzasi.zzdxs, zzasi.zzdxt, zzasi.zzdxu, zzasi.zzdxv, zzasi.zzbtk, zzasi.zzdxx), zza2.zzbln);
        return (zzacf) zza2.zzko().get();
    }
}
